updates:
- commit-message:
    prefix: fix
  directory: /
  package-ecosystem: npm
  schedule:
    interval: daily
- commit-message:
    prefix: fix
  directory: /
  package-ecosystem: github-actions
  schedule:
    interval: daily
version: 2
