name: "Unit Tests"

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
          RABBITMQ_DEFAULT_VHOST: /

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      svc:
        image: yusufali/servc
        ports:
          - 3000:3000
        env:
          CONF__HTTP__PORT: 3000
          CONF__BUS__ROUTE: test
          CONF__CACHE__URL: redis://redis
          CONF__BUS__URL: amqp://guest:guest@rabbitmq

    strategy:
      matrix:
        node-version:
          - lts/*
          - current

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npx prettier src/ --check

      - run: npm run build

      - run: |
          docker start $(docker ps -q)
          sleep 15

      - run: npm run-script test
        env:
          TEST_QUEUE: test
          API_URL: http://${{ github.server_url != 'https://github.com' && 'svc' || 'localhost' }}:3000
